version: '3'
services:
  database:
    image: mongo:4.0
    container_name: mongodb.api.cadastro
    ports:
      - 3000:3001
  backend:
    build: ./backend .
    container_name: backend.api.cadastro
    volumes:
      - ./backend:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
    ports:
      - 3002:3000
    depends_on:
      - database
    command: bash -c "npm i && npm start"